# -*- coding: utf-8 -*-
offset = 0x0C80

rev_code = {
    0xC81: "M",  # -
    0xC82: "x",  # ಂ
    0xC83: "X",  # ಃ
    0xC85: "a",  # ಅ
    0xC86: "A",  # ಆ
    0xC87: "i",  # ಇ
    0xC88: "I",  # ಈ
    0xC89: "u",  # ಉ
    0xC8A: "U",  # ಊ
    0xC8B: "WR",  # ಋ
    0xC8C: "",  # -
    0xC8D: "WA",  # -
    0xC8E: "e",  # ಎ
    0xC8F: "E",  # ಏ
    0xC90: "YE",  # ಐ
    0xC91: "WO",  # -
    0xC92: "o",  # ಒ
    0xC93: "O",  # ಓ
    0xC94: "YO",  # ಔ
    0xC95: "k",  # ಕ
    0xC96: "K",  # ಖ
    0xC97: "g",  # ಗ
    0xC98: "G",  # ಘ
    0xC99: "z",  # ಙ
    0xC9A: "c",  # ಚ
    0xC9B: "C",  # ಛ
    0xC9C: "j",  # ಜ
    0xC9D: "J",  # ಝ
    0xC9E: "Z",  # ಞ
    0xC9F: "T",  # ಟ
    0xCA0: "HT",  # ಠ
    0xCA1: "D",  # ಡ
    0xCA2: "HD",  # ಢ
    0xCA3: "N",  # ಣ
    0xCA4: "t",  # ತ
    0xCA5: "Ht",  # ಥ
    0xCA6: "d",  # ದ
    0xCA7: "Hd",  # ಧ
    0xCA8: "n",  # ನ
    0xCA9: "Q",  # -
    0xCAA: "p",  # ಪ
    0xCAB: "P",  # ಫ
    0xCAC: "b",  # ಬ
    0xCAD: "B",  # ಭ
    0xCAE: "m",  # ಮ
    0xCAF: "y",  # ಯ
    0xCB0: "r",  # ರ
    0xCB1: "R",  # ಱ
    0xCB2: "l",  # ಲ
    0xCB3: "L",  # ಳ
    0xCB4: "Hz",  # -
    0xCB5: "v",  # ವ
    0xCB6: "S",  # ಶ
    0xCB7: "Hs",  # ಷ
    0xCB8: "s",  # ಸ
    0xCB9: "h",  # ಹ
    0xCBC: "",  # -
    0xCBD: "",  # ಽ
    0xCBE: "A",  # ಾ
    0xCBF: "i",  # ಿ
    0xCC0: "I",  # ೀ
    0xCC1: "u",  # ು
    0xCC2: "U",  # ೂ
    0xCC3: "WR",  # ೃ
    0xCC5: "WA",  # -
    0xCC6: "e",  # ೆ
    0xCC7: "E",  # ೇ
    0xCC8: "YE",  # ೈ
    0xCC9: "WO",  # -
    0xCCA: "o",  # ೊ
    0xCCB: "O",  # ೋ
    0xCCC: "YO",  # ೌ
    0xCCD: "q",  # ್
    0xCD8: "Fk",  # -
    0xCD9: "FK",  # -
    0xCDA: "Fg",  # -
    0xCDB: "Fj",  # -
    0xCDC: "Fd",  # -
    0xCDD: "HR",  # -
    0xCDE: "FP",  # ೞ
    0xCDF: "Fy",  # -
}
