from revcode.meta.enums import Language


LANG_STR_ENUM_MAPPINGS = {
    "hindi": Language.Hindi,
    "hi": Language.Hindi,
    "punjabi": Language.Punjabi,
    "pa": Language.Punjabi,
    "kannada": Language.Kannada,
    "kn": Language.Kannada,
    "telugu": Language.Telugu,
    "te": Language.Telugu,
    "tamil": Language.Tamil,
    "ta": Language.Tamil,
    "assamese": Language.Assamese,
    "as": Language.Assamese,
    "bengali": Language.Bengali,
    "bn": Language.Bengali,
    "gujarati": Language.Gujarati,
    "gu": Language.Gujarati,
    "malayalam": Language.Malayalam,
    "ml": Language.Malayalam,
    "marathi": Language.Marathi,
    "mr": Language.Marathi,
    "oriya": Language.Oriya,
    "or": Language.Oriya,
    "english": Language.English,
    "en": Language.English,
    "hin": Language.Hindi,
    "pan": Language.Punjabi,
    "guj": Language.Gujarati,
    "mar": Language.Marathi,
    "kan": Language.Kannada,
    "tel": Language.Telugu,
    "tam": Language.Tamil,
    "mal": Language.Malayalam,
    "ori": Language.Oriya,
    "ben": Language.Bengali,
    "asm": Language.Assamese,
    "eng": Language.English,
}

LANG_ENUM_STR_MAPPINGS = {
    Language.Hindi: "hindi",
    Language.Punjabi: "punjabi",
    Language.Kannada: "kannada",
    Language.Telugu: "telugu",
    Language.Tamil: "tamil",
    Language.Malayalam: "malayalam",
    Language.Gujarati: "gujarati",
    Language.Marathi: "marathi",
    Language.Assamese: "assamese",
    Language.Oriya: "oriya",
    Language.Bengali: "bengali",
    Language.English: "english",
}

LANGUAGE_MAPPING = {
    "hindi": "hi",
    "punjabi": "pa",
    "gujarati": "gu",
    "marathi": "mr",
    "kannada": "kn",
    "telugu": "te",
    "tamil": "ta",
    "malayalam": "ml",
    "oriya": "or",
    "odiya": "or",
    "bengali": "bn",
    "assamese": "as",
    "english": "en",
}
